move to overlay fs

diff --git a/customize-img b/customize-img
--- a/customize-img
+++ b/customize-img
@@ -7,7 +7,7 @@ set -ex
 ##
 # usage
 function usage {
-  echo Usage: customize-img-[10.0.10.13] 
+  echo Usage: customize-img [kickstart_ip] [serial] [hostname]
 }
 
 ##
@@ -16,8 +16,8 @@ function customize_root {
   local root_dir=${1}
   local ip=${2}
 
-  # fstab
-  local fsline="${ip}:${root_dir}/ / nfs defaults,rw,nolock,errors=remount-ro 0 0"
+  # fstab - ro since overlayfs handles writes
+  local fsline="${ip}:${root_dir}/ / nfs defaults,ro,nolock,errors=remount-ro 0 0"
   echo "${fsline}" > ${root_dir}/etc/fstab
 
   # disable resizefs
@@ -30,12 +30,13 @@ function customize_boot {
   local boot_dir=${1}
   local ip=${2}
   local serial=${3}
+  local hostname=${4}
 
-  # cmdline.txt
-  local cmdline="console=serial0,115200 console=tty1 root=/dev/nfs nfsroot=${ip}:${root_dir},vers=3 rw ip=dhcp rootwait ds=nocloud;s=http://${ip}:8000/${serial}/"
+  # cmdline.txt - ro NFS root + overlay_host for per-node overlayfs
+  local cmdline="console=serial0,115200 console=tty1 root=/dev/nfs nfsroot=${ip}:${root_dir},vers=3 ro ip=dhcp rootwait overlay_host=${hostname} ds=nocloud;s=http://${ip}:8000/${serial}/"
   echo "${cmdline}" > ${boot_dir}/cmdline.txt
 
-  # customize firmeware (why? tbd)
+  # refresh firmware
   rm ${boot_dir}/start4.elf
   rm ${boot_dir}/fixup4.dat
   wget https://github.com/raspberrypi/rpi-firmware/raw/master/start4.elf -P ${boot_dir}/
@@ -43,16 +44,61 @@ function customize_boot {
 }
 
 ##
+# install_overlay_hook - inject overlayroot-nfs into the image's initramfs
+function install_overlay_hook {
+  local root_dir=${1}
+  local hook_dst=${root_dir}/etc/initramfs-tools/scripts/init-bottom/overlayroot-nfs
+
+  mkdir -p $(dirname ${hook_dst})
+  cp $(dirname $0)/overlayroot-nfs ${hook_dst}
+  chmod +x ${hook_dst}
+}
+
+##
+# rebuild_initramfs - chroot into the extracted image and run update-initramfs
+function rebuild_initramfs {
+  local root_dir=${1}
+  local host_arch=$(uname -m)
+  local qemu_bin=/usr/bin/qemu-aarch64-static
+
+  # Bind filesystems needed for chroot
+  mount -t proc  proc    ${root_dir}/proc
+  mount -t sysfs sysfs   ${root_dir}/sys
+  mount --bind   /dev    ${root_dir}/dev
+  mount --bind   /dev/pts ${root_dir}/dev/pts
+
+  # Cross-arch: copy qemu static binary for aarch64
+  if [ "${host_arch}" != "aarch64" ]; then
+    if [ ! -f ${qemu_bin} ]; then
+      apt-get install -y qemu-user-static > /dev/null
+    fi
+    cp ${qemu_bin} ${root_dir}/usr/bin/
+  fi
+
+  chroot ${root_dir} update-initramfs -u -k all
+
+  # Cleanup
+  umount ${root_dir}/dev/pts
+  umount ${root_dir}/dev
+  umount ${root_dir}/sys
+  umount ${root_dir}/proc
+  [ "${host_arch}" != "aarch64" ] && rm -f ${root_dir}/usr/bin/qemu-aarch64-static || true
+}
+
+##
 # customize image for netboot
 function customize-img {
   local kickstart_ip=${1:-"10.0.10.13"}
   local serial=${2:?"serial required"}
+  local hostname=${3:-${serial}}
   local root_dir
   read root_dir <<< $(./extract-img)
   local boot_dir=${root_dir}/boot
 
   customize_root ${root_dir} ${kickstart_ip}
-  customize_boot ${boot_dir} ${kickstart_ip} ${serial}
+  customize_boot ${boot_dir} ${kickstart_ip} ${serial} ${hostname}
+  install_overlay_hook ${root_dir}
+  rebuild_initramfs ${root_dir}
 
   echo ${root_dir}
 }
